# Cấu hình các đường dẫn tương đối dẫn đến thư mục Data, Metric, và Src

[paths.data]
origin_dir = "Data/Origin/data"
eda_dir = "Data/EDA"
eda_result_dir = "Data/EDA/result"
preprocess_dir = "Data/Preprocess Data/data"

[paths.files]
train_csv = "Data/Origin/data/train.csv"
features_csv = "Data/Origin/data/features.csv"
stores_csv = "Data/Origin/data/stores.csv"
test_csv = "Data/Origin/data/test.csv"
sample_submission_csv = "Data/Origin/data/sampleSubmission.csv"

processed_train_parquet = "Data/Preprocess Data/data/processed_train.parquet"
processed_test_parquet = "Data/Preprocess Data/data/processed_test.parquet"
processed_train_csv = "Data/Preprocess Data/data/processed_train.csv"
processed_test_csv = "Data/Preprocess Data/data/processed_test.csv"

[paths.metric]
dir = "Metric"

[paths.models.baseline]
dir = "Src/Baseline"
result_dir = "Src/Baseline/Result"

[paths.models.lightgbm]
dir = "Src/LightGBM"
checkpoint_dir = "Src/LightGBM/checkpoint"
result_dir = "Src/LightGBM/Result"

[paths.models.xgboost]
dir = "Src/XGBoost"
checkpoint_dir = "Src/XGBoost/checkpoint"
result_dir = "Src/XGBoost/Result"

[paths.models.catboost]
dir = "Src/CatBoost"
checkpoint_dir = "Src/CatBoost/checkpoint"
result_dir = "Src/CatBoost/Result"
